! Generated by make_vegetable_driver. DO NOT EDIT
program main
    implicit none

    call run()
contains
    subroutine run()
        use call_stack_entry_test, only: &
                call_stack_entry_call_stack_entry => test_call_stack_entry
        use call_stack_test, only: &
                call_stack_call_stack => test_call_stack
        use error_list_test, only: &
                error_list_error_list => test_error_list
        use message_list_test, only: &
                message_list_message_list => test_message_list
        use message_test, only: &
                message_message => test_message
        use vegetables, only: test_item_t, test_that, run_tests

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(5)

        individual_tests(1) = call_stack_entry_call_stack_entry()
        individual_tests(2) = call_stack_call_stack()
        individual_tests(3) = error_list_error_list()
        individual_tests(4) = message_list_message_list()
        individual_tests(5) = message_message()
        tests = test_that(individual_tests)

        call run_tests(tests)
    end subroutine
end program
